### ISSUE TITLE
Have you tried agave?

### ISSUE THREAD

**Issue by aasutossh** [sainnhe/icursive-nerd-font#1]
Hi, I am in love with https://github.com/agarick/agave, and I would kill to have icursive with it.
Thanks.

**Comment by sainnhe** [comment]
Everyone has their favorite font, I can't satisfy everyone.

I wrote a short guide to describe how to patch `iCursive` fonts, see [`PATCH.md`](https://github.com/sainnhe/icursive-nerd-font/blob/master/PATCH.md).

Btw, I was wondering whether I should upload binary files for fonts in the Op series because manually building is really painful, but I'm not sure if I should do so. What do you think?

**Comment by aasutossh** [comment]
Thanks for the article, I knew `alacritty` had feature like that, but didn't use it.

**Comment by aasutossh** [comment]
You added Fantasque Op and Dk? @sainnhe

**Comment by aasutossh** [comment]
The comments are italics but the keywords are not.
![image](https://user-images.githubusercontent.com/18498932/76783648-626c0800-67da-11ea-9944-cf0127d1b1ed.png)

**Comment by sainnhe** [comment]
Yeah, I just found it so lovely.

You need to set a global variable to 1 if you want to enable italics, see FAQ of my color schemes.

**Comment by aasutossh** [comment]
![image](https://user-images.githubusercontent.com/18498932/76812936-894c2d80-681e-11ea-8bd6-e0d0ee1794fb.png)
I should have mentioned earlier. I have it enabled(at the end of vimrc).
